In [1]:
import numpy as np

In [2]:
# Collect Data
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([[0], [1], [1], [0]])

In [3]:
print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [4]:
print y

[[0]
 [1]
 [1]
 [0]]


In [5]:
# build model
num_epochs = 60000

# initialize weights
syn0 = 2*np.random.random((3, 4)) - 1
syn1 = 2*np.random.random((4, 1)) - 1

In [6]:
print syn0

[[ 0.53537772  0.38937922  0.57778202  0.6702683 ]
 [ 0.9907902  -0.76276039  0.38414828 -0.9105208 ]
 [-0.96647634 -0.47652897 -0.84183076  0.91999747]]


In [7]:
print syn1

[[-0.83723008]
 [-0.99185323]
 [ 0.85646353]
 [ 0.2396103 ]]


In [8]:
def nonlin(x, deriv=False):
    if(deriv == True):
        return x*(1-x)
    
    return 1/(1 + np.exp(-x))

In [9]:
# Step 3 Train Model
for j in xrange(num_epochs):
    # Feed forward through layers 0, 1 and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # How much did we miss the target value?
    l2_error = y - l2
    
    if(j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
        
    # in what direction is the target value?
    l2_delta = l2_error * nonlin(l2, deriv=True)
    
    # How much did each 11 value contribute to 12 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * nonlin(l1, deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.501785998139
Error:0.00978965212128
Error:0.00670612038375
Error:0.00539831526769
Error:0.00463475014315
Error:0.00412041594749
