In [1]:
from scipy.stats import norm

In [2]:
norm.pdf(0)

0.3989422804014327

In [3]:
norm.pdf(0, loc=5, scale=10)

0.035206532676429952

In [4]:
import numpy as np

In [5]:
r = np.random.randn(10)
norm.pdf(r)

array([ 0.15739476,  0.3805196 ,  0.23676274,  0.39383892,  0.22232567,
        0.21124068,  0.3981021 ,  0.23853441,  0.38605745,  0.38346667])

In [6]:
norm.logpdf(r)

array([-1.84899824, -0.96621758, -1.44069672, -0.93181328, -1.50361197,
       -1.55475712, -0.92104676, -1.43324171, -0.95176909, -0.95850257])

In [7]:
norm.cdf(r)

array([ 0.08630551,  0.37923027,  0.15350253,  0.56374319,  0.13976774,
        0.87027011,  0.47411316,  0.15524311,  0.60111888,  0.38924126])

In [8]:
norm.logcdf(r)

array([-2.44986185, -0.96961168, -1.87403821, -0.57315647, -1.96777324,
       -0.13895164, -0.74630925, -1.86276294, -0.50896256, -0.94355592])