In [1]:
import tensorflow as tf

In [13]:
x = tf.constant(
    [1, 2, 3, 4],
    shape=(2, 2)
)

xT = tf.transpose(x)

einsum = tf.linalg.einsum('ij,ij->ij', x, x)
einsum_2 = tf.linalg.einsum('ij,jk->ik', xT, x)

In [14]:
print(x, xT, einsum, einsum_2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32) tf.Tensor(
[[10 14]
 [14 20]], shape=(2, 2), dtype=int32)


In [7]:
tf.square(x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [15]:
tf.matmul(xT, x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

## Reduce Sum

In [16]:
einsum_reduce = tf.linalg.einsum('ij,jk->', xT, x)

In [17]:
einsum_reduce

<tf.Tensor: shape=(), dtype=int32, numpy=58>

In [18]:
einsum_reduce = tf.linalg.einsum('ij,ij->', x, x)

In [19]:
einsum_reduce

<tf.Tensor: shape=(), dtype=int32, numpy=30>