### 1
Solving simultaneous equations is the process of finding the values of the variables (here $x$ and $y$) that satisfy the system of equations. Let's start with the simplest type of simultaneous equation, where we already know all but one of the variables:

$$3x−y=2$$

$$x = 4$$

Substitute the value of $x$ into the first equation to find $y$, then select the correct values of xx and yy below.

In [5]:
x = 4
y = -2 + 3 * x
y

10

### 2
The first goal when solving simple simultaneous equations should be to isolate one of the variables. For example, try taking the second equation away from the first to solve the following pair of equations:

$$3x - 2y = 7$$

$$2x - 2y = 2$$

What value did you find for xx? Now substitute xx into one of the equations to find yy, and select the correct pair below:

In [7]:
x = 7 - 2
y = (7 - 3 * x) / -2
x, y

(5, 4.0)

### 3
This method is called elimination, and you can use it even when the coefficients, the numbers in front of xx and yy, aren't the same.

For example, to solve the following equations try multiplying both sides of the first equation by 22, then solve using the same method as the last question.

$$3x - 2y = 4$$

$$6x + 3y = 15$$

Select the correct values of xx and yy below:

In [8]:
# 2* (3𝑥−2𝑦=4) -  6𝑥+3𝑦=15
# 0x -4y -3y = 8 - 15
# -7y = -7
y = 7/7
x = (4 + 2 *y) / 3
x, y

(2.0, 1.0)

### 4
A very similar technique can be used to find the inverse of a matrix, which you will learn about in week three of this course.

There is also the substitution method, where we rearrange one of the equations to the form x = ay+bx=ay+b or y = cx+dy=cx+d and then substitute xx or yy into the other equation. Use any method you'd like to solve the following simultaneous equations:

$$-2x + 2y = 20$$

$$5x + 3y = 6$$

Select the correct values of xx and yy below:

In [9]:
# y = (20 + 2x) / 2 => y =  10 + x
# 5 * x + 3 (10 + x) = 6
# 5x + 30 + 3x = 6 => 8x = -24
x = -3
y = 10 + x
x, y

(-3, 7)

### 5
Systems of simultaneous equations can have more than two unknown variables. Below there is a system with three; xx, yy and zz. First try to find one of the variables by elimination or substitution, which will lead to two equations and two unknown variables. Continue the process to find all of the variables.

Which values of xx, yy and zz solve the following equations?

3x - 2y + z = 7

x + y + z = 2

3x - 2y - z = 3

Before you move on you might like to think about how many equations you would need to uniquely determine four, five, or more variables. Are there are any other rules for how the equations have to be related? In week two of this course you will learn about linear independence, which is very closely related to this.

In [14]:
import numpy as np
A = np.array([[3, -2, 1], [1, 1, 1], [3, -2, -1]])
a = np.array([7, 2, 3])

[x, y, z] = a / A

In [15]:
x, y, z

(array([ 2.33333333, -1.        ,  3.        ]),
 array([7., 2., 3.]),
 array([ 2.33333333, -1.        , -3.        ]))

In [16]:
A * [x, y, z]

array([[7., 2., 3.],
       [7., 2., 3.],
       [7., 2., 3.]])

In [17]:
np.invert(A) * a

array([[-28,   2,  -6],
       [-14,  -4,  -6],
       [-28,   2,   0]])

In [20]:
np.add([1, -2], [-2, 1])

array([-1, -1])

In [21]:
np.subtract([-1, 2], [1, -2])

array([-2,  4])

In [24]:
np.square([1, 3, 4, 2])

array([ 1,  9, 16,  4])

In [25]:
np.sum(np.square([1, 3, 4, 2]))

30

In [27]:
np.array([-5, 3, 2, 8]) @ np.array([1, 2, -1, 0])

-1

In [36]:
r = np.array([3, -4, 0])
s = np.array([10, 5, -6])

r @ s 

10

In [39]:
np.abs(3)

3