## Changing Basis
Changing from the standard basis to a basis consisting of orthogonal vectors.

![Changing Basis](201_Changing_Basis.png)

In [1]:
import numpy as np

### 1
Written in the standard basis, what is $\mathbf{v}$ in the basis defined by $\mathbf{b_1}$ and $\mathbf{b_2}$
You are given that $\mathbf{b_1}$ and $\mathbf{b_2}$ are orthogonal to each other.

In [2]:
v = np.array([10, -5])
b_1 = np.array([3, 4])
b_2 = np.array([4, -3])

$ c_1(b_1) + c_2(b_2) = v $  
$ c_1(3, 4) + c_2(4, -3) = (10, -5) $  
$ 3c_1 + 4c_2 = 10 $  
$ 4c_1 - 3c_2 = -5 $  

$ 9c_1 + 16c_1 = 30 - 20 $  
$ 25c_1 = 10 $  
$ c_1= 2/5 $  

$ 3(2/5) + 4c_2 = 10 $  
$ 4c_2 = 10 - 6/5 $  
$ c_2 = 11/5 $  

Hence c is `[2/5, 11/5]`

### 2

In [3]:
v = np.array([5, -1])
b_1 = np.array([1, 1])
b_2 = np.array([1 -1])

$ c_1(b_1) + c_2(b_2) = v $  
$ c_1(1, 1) + c_2(1, -1) = (5, -1) $  
$ c_1 + c_2 = 5 $  
$ c_1 - c_2 = -1 $  

$ 2c_1 = 5 - 1 $  
$ c_1 = 2 $  

$ 2 + c_2 = 5 $  
$ c_2 = 3 $ 

Hence c is `[2, 3]`

### 3

In [4]:
v = np.array([2, 2])
b_1 = np.array([-3, 1])
b_2 = np.array([1, 3])

$ c_1(b_1) + c_2(b_2) = v $  
$ c_1(-3, 1) + c_2(1, 3) = (2, 2) $  
$ -3c_1 + c_2 = 2 $  
$ c_1 + 3c_2 = 2 $  

$ c_2 + 9c_2 = 2 + 6 $  
$ c_2 = 4/5 $   

$ -3(c_1) + 4/5 = 2 $  
$ -3c_1 = 2 - 4/5 $  
$ c_2 = -2/5 $  

Hence c is `[-2/5, 4/5]`

### 4

In [5]:
v = np.array([1, 1, 2, 3])
b_1 = np.array([1, 0, 0, 0])
b_2 = np.array([0, -2, -1, 0])
b_3 = np.array([0, 1, 2, 0])
b_4 = np.array([0, 0, 0, 3])

b = np.array([b_1, b_2, b_3, b_4])

In [6]:
b

array([[ 1,  0,  0,  0],
       [ 0, -2, -1,  0],
       [ 0,  1,  2,  0],
       [ 0,  0,  0,  3]])

In [7]:
v_v = [1, 0, 1, 1]

b.T @ v_v

array([1, 1, 2, 3])

### 5

In [8]:
v = np.array([1, 1, 1])
b_1 = np.array([2, 1, 0])
b_2 = np.array([1, -2, -1])
b_3 = np.array([-1, 2, -5])

In [9]:
a_1 = np.array([3/5, -1/3, -2/15])
a_2 = np.array([3, -1, -2])
a_3 = np.array([-3/5, -1/3, 2/15])
a_4 = np.array([-3/5, -1/3, -2/15])

b = np.array([b_1, b_2, b_3])

In [10]:
print(b.T @ a_1)
print(b.T @ a_2)
print(b.T @ a_3)
print(b.T @ a_4)

[1. 1. 1.]
[ 7  1 11]
[-1.66666667  0.33333333 -0.33333333]
[-1.4 -0.2  1. ]


### 6

In [11]:
v = np.array([-4, -3, 8])
b_1 = np.array([1, 2, 3])
b_2 = np.array([-2, 1, 0])
b_3 = np.array([-3, -6, 5])

In [12]:
a_1 = np.array([1, 1, 1])
a_2 = np.array([0, 1, 1])
a_3 = np.array([1, 0, 1])
a_4 = np.array([1, 1, 0])

b = np.array([b_1, b_2, b_3])

In [13]:
print(b.T @ a_1)
print(b.T @ a_2)
print(b.T @ a_3)
print(b.T @ a_4)

[-4 -3  8]
[-5 -5  5]
[-2 -4  8]
[-1  3  3]
