In [1]:
import numpy as np

## 1

In [11]:
r = np.array([[3], [2]])
A = np.array([[1/2, -1], [0, 3/4]])

In [14]:
r_ = A @ r
r_

array([[-0.5],
       [ 1.5]])

## 2

In [17]:
r = np.array([[-2], [4]])
A = np.array([[1/2, -1], [0, 3/4]])

In [18]:
A @ r

array([[-5.],
       [ 3.]])

## 3

In [19]:
A = np.array([[-1/2, 1/2], [1/2, 1/2]])
e_1 = np.array([[1], [0]])
e_2 = np.array([[0], [1]])

In [21]:
tr_1 = A @ e_1
tr_1

array([[-0.5],
       [ 0.5]])

In [22]:
tr_2 = A @ e_2
tr_2

array([[0.5],
       [0.5]])

## 4

In [33]:
A = np.array([[1, 1, 3],[1, 2, 4],[1, 1, 2]])
np.linalg.inv(A)

array([[ 0., -1.,  2.],
       [-2.,  1.,  1.],
       [ 1., -0., -1.]])

In [34]:
A @ np.linalg.inv(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5

You go to the shops on Monday and buy 1 apple, 1 banana, and 1 carrot; the whole transaction totals €15. On Tuesday you buy 3 apples, 2 bananas, 1 carrot, all for €28. Then on Wednesday 2 apples, 1 banana, 2 carrots, for €23.

In [58]:
A = np.array([[1, 1, 1],[3, 2, 1],[2, 1, 2]])
r = np.array([[15],[28],[23]])

A_inv = np.linalg.inv(A)

In [59]:
s = A_inv @ r
s

array([[3.],
       [7.],
       [5.]])

In [40]:
A_inv

array([[-1.5,  0.5,  0.5],
       [ 2. ,  0. , -1. ],
       [ 0.5, -0.5,  0.5]])

## 6

In [41]:
A = np.array([[1, 3/2, 1/2],[0, 1, 1],[2, 8, 13]])
s = np.array([[9/4], [1/2], [2]])       

In [42]:
np.linalg.inv(A) @ s

array([[ 0.78571429],
       [ 1.21428571],
       [-0.71428571]])

In [43]:
9/4

2.25

## 7

In [47]:
r = A @ np.array([[3],[-1/2],[0]])

In [52]:
np.array([[1,0, 0],[0, 1, 0],[0, 0, 1]]) @ r

array([[ 2.25],
       [-0.5 ],
       [ 2.  ]])

In [51]:
r

array([[ 2.25],
       [-0.5 ],
       [ 2.  ]])

## 8

In [53]:
A = np.array([[-1.5, 0.5, 0.5],
     [2, 0, -1],
     [0.5, -0.5, 0.5]])
s = np.array([[3], [7], [5]])

In [54]:
A

array([[-1.5,  0.5,  0.5],
       [ 2. ,  0. , -1. ],
       [ 0.5, -0.5,  0.5]])

In [56]:
r = np.linalg.inv(A) @ s
r

array([[15.],
       [28.],
       [23.]])

In [57]:
np.linalg.inv(A)

array([[1., 1., 1.],
       [3., 2., 1.],
       [2., 1., 2.]])