In [1]:
import numpy as np

In [2]:
def is_singular(A):
    B = np.array(A, dtype=np.float_)
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

class MatrixIsSingular(Exception): pass

In [3]:
def fixRowZero(A):
    if(A[0, 0] == 0):
        A[0] = A[0] + A[1]
    if(A[0, 0] == 0):
        A[0] = A[0] + A[2]
    if(A[0, 0] == 0):
        A[0] = A[0] + A[3]
    if(A[0, 0] == 0):
        raise MatrixIsSingular()
    A[0] = A[0] / A[0, 0]
    print(A)
    return A

In [4]:
def fixRowOne(A):
    A[1] = A[1] - A[1, 0] * A[0]
    if(A[1, 1] == 0):
        A[1] = A[1] + A[0]
        A[1] = A[1] - A[1, 0] * A[0]
    if(A[1, 1] == 0):
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1, 0] * A[0]
    if(A[1, 1] == 0):
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1, 0] * A[0]
    if(A[1, 1] == 0):
        raise MatrixIsSingular()
    A[1] = A[1] / A[1, 1]
    print(A)
    return A

In [5]:
def fixRowTwo(A):
    A[2] = A[2] - A[2, 0] * A[0]
    A[2] = A[2] - A[2, 1] * A[1]
    if(A[2, 2] == 0):
        A[2] = A[2] + A[3]
        
        A[2] = A[2] - A[2, 0] * A[0]
        A[2] = A[2] - A[2, 1] * A[1]
        
    if(A[2, 2] == 0):
        raise MatrixIsSingular()
    A[2] = A[2] / A[2, 2]
    print(A)
    return A

In [6]:
def fixRowThree(A):
    A[3] = A[3] - A[3, 0] * A[0]
    A[3] = A[3] - A[3, 1] * A[1]
    A[3] = A[3] - A[3, 2] * A[2]
    
    if(A[3, 3] == 0):
        raise MatrixIsSingular()
        
    A[3] = A[3] / A[3, 3]
    print(A)
    return A

In [7]:
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
is_singular(A)

[[1. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 4. 4.]
 [0. 0. 5. 5.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 4. 4.]
 [0. 0. 5. 5.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 5. 5.]]


True