# Basic Tensors

In [2]:
import tensorflow as tf
import numpy as np

## Tensor Operations

In [3]:
# Create a 1D uint8 NumPy array comprising of first 25 natural numbers
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
# Convert NumPy to Tensor object
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [5]:
# Square the input tensor x
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [6]:
tf.math.square(x)

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([     0,      1,     16,     81,    256,    625,   1296,   2401,
         4096,   6561,  10000,  14641,  20736,  28561,  38416,  50625,
        65536,  83521, 104976, 130321, 160000, 194481, 234256, 279841,
       331776])>

In [7]:
# Reshape a tensor
x = tf.reshape(x, (5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

Notice theat you will get an error message if you choose a shape that cannot be exactly filled with the values of the given tensor
- Run the cell below and look at the error message
- Try to change the tuple that is passed to `shape` to avoid an error

In [21]:
# Try thi and look at the error
# Try to change the input to `shape` to avoid an error

tmp = tf.constant([1, 2, 3, 4])
try:
    
    tf.reshape(tmp, shape=(2, 3))
except tf.errors.InvalidArgumentError as v:
    print(v)

Input to reshape is a tensor with 4 values, but the requested shape has 6 [Op:Reshape]


In [10]:
# Change data type
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

## Broadcast - Single value 

In [11]:
# Lets define a constant and see how broadcasting works in the following cell
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [12]:
# Broadcasting in action
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [13]:
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [16]:
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [15]:
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

## Shape of `tf.constant`

In [17]:
tf.constant([1, 2, 3, 4], shape=(2, 2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Shape of `tf.Variable`

In [18]:
try:
    tf.Variable([1, 2, 3, 4], shape=(2, 2))
except ValueError as v:
    print(v)

The initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).
