# Gradient Tape 1

- Gradient Tapes are automatic differentiation APIs

In [2]:
import tensorflow as tf
import numpy as np

In [5]:
x_train = np.array([-1, 0, 1.0, 2.0, 3.0, 4.0], dtype=float)
y_train = 2*x_train - 1
y_train

array([-3., -1.,  1.,  3.,  5.,  7.])

In [7]:
# Trainable Variables
w = tf.Variable(np.random.random(), trainable=True)
b = tf.Variable(np.random.random(), trainable=True)

In [10]:
LEARNING_RATE = 0.001
def simple_loss(real_y, pred_y):
    return tf.abs(real_y - pred_y)

def fit_data(real_x, real_y):
    with tf.GradientTape(persistent=True) as tape:
        # Make Prediction
        pred_y = w * real_x + b
        # Calculate loss
        reg_loss = simple_loss(real_y, pred_y)
        
    # Calculate gradients
    w_gradient = tape.gradient(reg_loss, w)
    b_gradient = tape.gradient(reg_loss, b)
    
    # Update variables
    w.assign_sub(w_gradient * LEARNING_RATE)
    b.assign_sub(b_gradient * LEARNING_RATE)

In [13]:
for _ in range(500):
    fit_data(x_train, y_train)
    
print(f'y ~ {w.numpy()}x + {b.numpy()}')

y ~ 2.0039682388305664x + -0.998036801815033


## Gradient Descent with `tf.GradientTape`

- `logits` refer to a vector of raw prediction value for each category and a multi-class classification
- Logits are fed into a `softmax` function to turn them into probability for each category

In [ ]:
def train_step(images, labels):
    
    with tf.GradientTape() as tape:
        logits = model(images, training=True)
        loss_value = loss_object(labels, logits)
        
    loss_history.append(loss_value.numpy().mean())
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

## Gradient Computation with Tensorflow
$$\frac{d}{dw}w^2 =2w$$

In [18]:
def calc_derivative(w_val):
    w = tf.Variable([[w_val]])
    with tf.GradientTape() as tape:
        loss = w *w

    return tape.gradient(loss, w)

In [20]:
calc_derivative(1.0)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [21]:
calc_derivative(2.0)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>