# Gradient Tape: Tensorflow

In [1]:
import tensorflow as tf

In [2]:
x = tf.ones((2, 2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [3]:

with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.reduce_sum(x)
    z = tf.square(y)
    
dz_dx = tape.gradient(z, x)

In [4]:
dz_dx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

## From the above code...
$$y = \sum x$$
$$y=x_{1,1} + x_{1,2} + x_{2,1} + x_{2,2} \tag{1}$$
$$z=y^2\tag{2}$$

In [5]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>



$$\frac{\partial z}{\partial x} = \frac{\partial z}{\partial y} \times \frac{\partial y}{\partial x}$$
from equation 2
$$\frac{\partial z}{\partial y} = 2 \times y = 8$$
from equation 1
$$\frac{\partial y}{\partial x}= \frac{\partial y}{\partial x_{1,1}}, \frac{\partial y}{\partial x_{1,2}}, \frac{\partial y}{\partial x_{2,1}}, \frac{\partial y}{\partial x_{2,2}}$$
$$\frac{\partial y}{\partial x}= [[1, 1], [1, 1]] $$
hence
$$\frac{\partial z}{\partial x} = \frac{\partial z}{\partial y} \times \frac{\partial y}{\partial x} = [[8, 8], [8, 8]]$$


In [6]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

## Using `Persistent=True`

$$y = x^2 \tag{1}$$
$$z = y^2 \tag{2}$$

In [10]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y = x ** 2
    z = y ** 2
    
dz_dx = tape.gradient(z, x)
dy_dx = tape.gradient(y, x)

#del tape

$$\frac{\partial z}{\partial x} = \frac{\partial z}{\partial y} \times \frac{\partial y}{\partial x}$$
from equation 2
$$\frac{\partial z}{\partial y} = 2 \times y = 2 \times 3^2 = 18$$
$$\frac{\partial y}{\partial x} = 2x = 2 \times 3 = 6$$
hence
$$\frac{\partial z}{\partial x} = \frac{\partial z}{\partial y} \times \frac{\partial y}{\partial x} = 18 \times 6 = 108$$


by substitution
$$\frac{\partial z}{\partial x}= \frac{\partial}{\partial x}x^4$$
$$\frac{\partial z}{\partial x}= 4x^3 = 4 \times 3^3 = 108 $$

In [11]:
dz_dx

<tf.Tensor: shape=(), dtype=float32, numpy=108.0>

In [12]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

## Derivative of a Derivative, $2^{nd}$ Derivative
$$y=x^3$$
$$\frac{\partial y}{\partial x} = 3x^2$$
$$\frac{\partial^2 y}{\partial x^2}=6x$$

In [13]:
x = tf.Variable(1.0)
with tf.GradientTape() as tape_2:
    with tf.GradientTape() as tape_1:
        y = x ** 3
    dy_dx = tape_1.gradient(y, x)
d2y_dx2 = tape_2.gradient(dy_dx, x)

In [14]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [15]:
d2y_dx2

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>