In [1]:
import numpy as np

 ### Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.12.1
lapack_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
blis_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE


### Create a null vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


 ### How to get documentation of numpy add function

#### python -c "import numpy; numpy.info(numpy.add)"

### Create a null vector of size 10 but the fifth value which is 1

In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### Create a vector with values ranging from 10 to 49

In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Reverse a vector (first element becomes last)

In [6]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
M = np.array(([0, 1, 2], [3, 4, 5], [6, 7, 8]))
print M
M = np.arange(9).reshape((3, 3))
print M

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
Z = np.array([1,2,0,0,4,0])
nonZeros = np.nonzero(Z)
print(nonZeros)

(array([0, 1, 4]),)


In [9]:
M = np.array(([1, 1, 2], [0, 4, 5], [0, 7, 8]))
print(np.nonzero(M))

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 1, 2, 1, 2]))


### 3x3 Identity Matrix

In [10]:
Z = np.eye(3)
print Z

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
