In [1]:
import numpy as np

### Create a 3x3x3 array with random values

In [2]:
Z = np.random.random((3, 3, 3))
Z

array([[[ 0.25896927,  0.4156209 ,  0.01375171],
        [ 0.64865239,  0.45104759,  0.88146226],
        [ 0.90851906,  0.03975478,  0.465338  ]],

       [[ 0.42693973,  0.75432424,  0.24664075],
        [ 0.53646466,  0.79452196,  0.22372186],
        [ 0.51241901,  0.80242896,  0.2867063 ]],

       [[ 0.75610817,  0.16686564,  0.49659728],
        [ 0.12714333,  0.21669417,  0.77254398],
        [ 0.20202152,  0.70544277,  0.39832728]]])

### Create a 10x10 array with random values and find the minimum and maximum value

In [3]:
Z = np.random.random((10, 10))
mn = Z.min()
mx = Z.max()
print mn, mx

0.00886536060751 0.98624233547


### Create a random vector of size 30 and find the mean value

In [4]:
Z = np.random.random((10, 10))
mn = Z.mean()
md = np.median(Z)
sd = np.sqrt(Z.var())
print mn, md, sd

0.506010875403 0.449272207832 0.298814417694


### Create a 2d array with 1 on the border and 0 inside

In [5]:
Z = np.ones((10, 10))
print Z
Z[1:-1,1:-1] = 0
print Z

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### What is the result of the following expression?

In [6]:
0 * np.nan # np.nan

nan

In [7]:
np.nan = np.nan # crash

In [8]:
np.inf > np.nan # False

False

In [9]:
np.nan - np.nan # np.nan

nan

In [10]:
0.3 == 3 * 0.1 # True

False

### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
I = np.eye(5, 5)
I

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [12]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Create a 8x8 matrix and fill it with a checkerboard pattern 

In [13]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 ### Create a 8x8 matrix and fill it with a checkerboard pattern

In [14]:
print np.unravel_index(100, (6, 7, 8))

(1, 5, 4)


### Create a checkerboard 8x8 matrix using the tile function

In [15]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Normalize a 5x5 random matrix

In [16]:
Z = np.random.random((5, 5))
print Z
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print Z

[[ 0.89132942  0.76064296  0.89004393  0.53166964  0.07426912]
 [ 0.37651651  0.56806542  0.11941382  0.41940746  0.60643687]
 [ 0.73967044  0.28035115  0.4294056   0.22575349  0.96680869]
 [ 0.87679433  0.67831866  0.89571915  0.18688155  0.66797393]
 [ 0.75053405  0.32524551  0.77031356  0.51117922  0.26563431]]
[[ 0.91543314  0.76901223  0.91399288  0.51247086  0.        ]
 [ 0.33863752  0.55324863  0.05058005  0.38669249  0.59623996]
 [ 0.74551465  0.23089399  0.39789438  0.16972286  1.        ]
 [ 0.89914806  0.6767762   0.92035139  0.12617079  0.66518598]
 [ 0.75768622  0.28119357  0.77984715  0.48951343  0.21440527]]
